### ISSUE TITLE
Increase Pot threshold

### ISSUE THREAD

**Issue by ricardoquesada** [crystalct/5plusbuttonsJoystick#1]
Hi,

Thanks for the great work!
Any chance to increase the Pot threshold from `<8` to something like `<16` ?

Some existing games / applications seems to have a higher threshold:
- https://csdb.dk/release/?id=179703
- https://csdb.dk/release/?id=219408

And I already have a joystick but I can't get Pot values as low as 7... I can only get ~10... that's why I'm asking whether it is possible to use values like <16 for the button2 and button3.

Thanks!

**Comment by ricardoquesada** [comment]
I noticed that Super Mario also has a higher threshold value... not sure what value it is using, but it must be > 10.

**Comment by crystalct** [comment]
I think there are Joystick that aren't Zero Ohm between POT and VCC when button is pressed.... i will change (slowly) the code inside games to modify threshold (button is pressed when value is < 16). What are your preferred games? So i start from them.

**Comment by ricardoquesada** [comment]
Many Thanks.

- Green Beret
- 1942
- Turrican 2


Notice: I've just tested Turbo Charge and it also works Ok with my joystick.. I'm guessing that all original GS games have higher threshold (?)... I wonder if Commodore had a "recommended threshold" for the buttons

**Comment by crystalct** [comment]
Do you have a tester to get how many ohms there are between POTX and VCC when 2nd button is pressed?

**Comment by ricardoquesada** [comment]
It is not a regular joystick... it is an adapter that I made that I needed to add a pull-up with 8.2K Ohm resistor... I'll attach the schematic later tonight.

**Comment by ricardoquesada** [comment]
It is this device: https://github.com/ricardoquesada/unijoysticle2/blob/main/docs/schematic_unijoysticle2_c64.pdf

In particular the resistors R13-R17 are controlling the pull-ups (page 4). Perhaps if I lower the value a bit I might be able to get to Pot values < 8..

I plan to support the "start" and "select" buttons that you defined as well.

**Comment by crystalct** [comment]
Put your joypad in the adapter, you shoud be able to test resistance....put 5 V on DB9 pin 7 and GND on DB9 pin 8, push button that could be 2nd button and test resistance between pin 7 & 9...just for curiosity

**Comment by crystalct** [comment]
pot x threshold increased from 0 to 15 for Green Beret

**Comment by ricardoquesada** [comment]
Thanks. works great!

The resistance that I measured was: 
 - 7.8K Ohm:   Negative probe on Pin 7,  Positive probe on Pin 9
 - 8.4K Ohm : Negative probe on Pin 9,  Positive probe on Pin 7

What resistance does your joystick have?

**Comment by crystalct** [comment]
![bitmoji](https://sdk.bitmoji.com/render/panel/8d19f756-d72a-4ddb-82bc-01420fd1760a-888af1ad-9072-4a68-8915-4e015bf57555-v1.png?transparent=1&palette=1&width=246)
with 2nd fire button pressed. less than 1 ohm

**Comment by ricardoquesada** [comment]
I was expecting a high value because my design is a bit different in the sense that I'm using a v3.3 MCU... and I don't want to directly connect the MCU to the C64... so I'm using Pull-up in a 7405 (Open collector). The resistor is 8.2K... so it matches the values that we are seeing.

I play with different values a bit more... perhaps I can get to ~5 in the Pot

**Comment by ricardoquesada** [comment]
Using 2.7K Ohm (instead of 8.2K) I can get to pot values as low as 4.

Your Tester program (which is comparing with values <7 works.

What threshold value are you using for your patched games? are you comparing for Pot < 7 ? or simply 0?

Although I can try with lower resistor values, I prefer to be on the safer side as recommended here:
http://wiki.icomp.de/wiki/File:JoystickMod.jpg
... and use a 2.7K resistor

**Comment by crystalct** [comment]
I'll keep a threshold from 0 to 15. 
It is very reasonable and I think nobody will ever use POTX (or POTY) to get more than 4 values ​​(and therefore 4 different buttons each). 256/4 = 64. I'll update Joystick5plus1Test.prg

**Comment by crystalct** [comment]
I would be truly honored if you sent me a unit. Sen me a message to my mail crystal@unict.it and i will send you my address.

**Comment by crystalct** [comment]
1942 Updated

**Comment by crystalct** [comment]
Old issue
