### ISSUE TITLE
SUB-D Connector wrong Pin Layout?

### ISSUE THREAD

**Issue by venice1200** [crystalct/5plusbuttonsJoystick#2]
Hi,
after our discussion in the Forum64 i orderred some of the last version PCB's (with C64/Amiga Support).
I solderred a SUB-D 9pin Female connector to the matching Pins to the PCB.
I connected a Joystick and the Buttons 1+2 in C64 mode but got really weird results.
Joystick Down results in Button3 and some other strange things.

Next, I connected a cable directly to pins 1-9 on the opposite side of the SUB-D connector.
That works correctly.

I am the opinion that the Pinout of the SUB-D Pins on the PCB is for a male connector, not a for a female connector.
Please double check!

![IMG_0178](https://github.com/crystalct/5plusbuttonsJoystick/assets/43762187/8704e176-dbd7-4a5c-87f4-bf455ab3c341)

![PCB_SubD_9pin_Female](https://github.com/crystalct/5plusbuttonsJoystick/assets/43762187/ec05b265-f8ba-4478-a13e-7bda302aa238)

**Comment by crystalct** [comment]
doh!!
it's true.... sorry. I need to fix the gerber ASAP.
I always use the cable and not the extension....I would have noticed this stupid mistake sooner.

**Comment by venice1200** [comment]
If you can, add some more (isolated) mounting wholes onto the PCB. 
At least one more on the SUB-D site. Gives a cable connection more stabilty.

**Comment by venice1200** [comment]
New Version available, closed.
